// Cross-language byte-compatibility tests.
//
// The expected values are generated by the Rust side:
//   cargo run -p veilux-sdk --example vectors
// If the kernel's signing format ever changes, regenerate and update here.

import { test } from "node:test";
import assert from "node:assert/strict";
import {
  PartyIdentity,
  builders,
  signingBytes,
  toHex,
  tokenId as deriveTokenId,
} from "../dist/index.js";

const ALICE_SEED = new Uint8Array(32).fill(1);
const ALICE_PUBKEY = "8a88e3dd7409f195fd52db2d3cba5d72ca6709bf1d94121bf3748801b40f6f5c";
const TOKEN_ID = "0xfebdbcd19fcfe4e3d1fd12fdaa4706c6652843da5885897eb0d935477fc4f034";

const CREATE = {
  signing_bytes:
    "7665696c75782f636f6d6d616e642f7631ff746f6b656eff616c696365ff0000000000000000225075626c696322ff7b226f70223a22637265617465222c226e616d65223a22476f6c6420436f696e222c2273796d626f6c223a22474c44222c22646563696d616c73223a31382c22696e697469616c5f737570706c79223a2231303030303030222c226d696e7461626c65223a747275657d",
  command_id: "0x844cfe081c7204b41d56b68a37a1a888eb7e243685c3b0eca43c3fb4f2569af3",
  signature:
    "63aa86214e1a6d0a796f4d67ddac81bb2fba8423db937a6162ec055cf6ddeb41ce26f759bece9ba8092836a06e33db24cb5eea179810b23d99248fc412315b01",
};

const TRANSFER = {
  signing_bytes:
    "7665696c75782f636f6d6d616e642f7631ff746f6b656eff616c696365ff01000000000000007b2250617274696573223a5b22616c696365222c22626f62225d7dff7b226f70223a227472616e73666572222c22746f6b656e5f6964223a5b3235342c3138392c3138382c3230392c3135392c3230372c3232382c3232372c3230392c3235332c31382c3235332c3137302c37312c362c3139382c3130312c34302c36372c3231382c38382c3133332c3133372c3132362c3137362c3231372c35332c37312c3132372c3139362c3234302c35325d2c22746f223a22626f62222c22616d6f756e74223a22323530303030227d",
  command_id: "0x250337cfb424c01eb800f8d3823168b7226ae191314aaf8b54fa9a4ca47a4b81",
  signature:
    "55ef92b2ad7d9068c4a8e5144bf5ae6fb1dde0df6ebaef50dc17414ade00df65eaffcdca93e0d80236aefa9fa384ab3ba96cbe15b1f26019430646adf26c370e",
};

function bytesToHex(b: number[]): string {
  return b.map((x) => x.toString(16).padStart(2, "0")).join("");
}

test("public key derivation matches Rust", () => {
  const alice = PartyIdentity.fromSeed("alice", ALICE_SEED);
  assert.equal(bytesToHex(Array.from(alice.publicKey())), ALICE_PUBKEY);
});

test("token id derivation matches Rust", () => {
  assert.equal(deriveTokenId("alice", "GLD", "Gold Coin"), TOKEN_ID);
});

test("token_create: signing bytes, id, and signature match Rust", () => {
  const alice = PartyIdentity.fromSeed("alice", ALICE_SEED);
  const cmd = builders.tokenCreate("alice", "Public", 0, "Gold Coin", "GLD", 18, 1_000_000n, true);

  assert.equal(toHex(signingBytes(cmd)).slice(2), CREATE.signing_bytes);

  const signed = alice.sign(cmd);
  assert.equal(bytesToHex(signed.signature), CREATE.signature);
});

test("token_transfer (private): signing bytes and signature match Rust", () => {
  const alice = PartyIdentity.fromSeed("alice", ALICE_SEED);
  const cmd = builders.tokenTransfer(
    "alice",
    { Parties: ["alice", "bob"] },
    1,
    TOKEN_ID,
    "bob",
    250_000n,
  );

  assert.equal(toHex(signingBytes(cmd)).slice(2), TRANSFER.signing_bytes);

  const signed = alice.sign(cmd);
  assert.equal(bytesToHex(signed.signature), TRANSFER.signature);
});
