title: VEILUX
description: A featherweight, privacy-first, AI-native Layer-1 blockchain written in Rust.
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM

defaults:
  - scope:
      path: ""
    values:
      layout: default
